# Generated by Django 3.2.9 on 2021-11-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='posts',
            field=models.ManyToManyField(blank=True, to='usuario.Post'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, to='usuario.Post'),
        ),
    ]
