# Generated by Django 3.2.9 on 2021-11-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_post_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='usuario.Categoria'),
        ),
    ]
