# Generated by Django 3.2.9 on 2021-11-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20211120_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
